name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ghidra_version:
        description: 'Specify the Ghidra version(s) you want to build for (e.g. "latest", "11.0")'
        required: true
        default: '"latest"'
  schedule:
    - cron: '0 0 1 * *' # Monthly
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ghidra: ${{ fromJSON(format('[{0}]', inputs.ghidra_version || '"latest","11.4.2","11.4.1","11.4","11.3.2","11.3.1","11.3","11.2.1","11.2","11.1.2","11.1.1","11.1","11.0.3","11.0.2","11.0.1","11.0"')) }}

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Install Ghidra ${{ matrix.ghidra }}
      uses: antoniovazquezblanco/setup-ghidra@v2.0.4
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Build
      run: gradle

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BinDiffHelper_Ghidra_${{ matrix.ghidra }}
        path: dist/*.zip

  release:
    runs-on: "ubuntu-latest"
    needs: build
    if: contains(github.ref, 'refs/tags/v')

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4

    - name: Release stable
      if: contains(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "BinDiffHelper ${{github.ref_name}}"
        files: BinDiffHelper_Ghidra_*/*.zip
